=== mediafreak/jpr_web_sose13_abschlussprojekt/xml/sitemap/sitemap.dtd
<!-- Elementtyp-Deklaration:
     PCDATA:             Schluesselwort fuer einen Textblock, der auch weitere Anweisungen an den Parser enthalten kann
     +                   Element ist obligatorisch und wiederholbar, muss also mindestens einmal oder beliebig oft auftreten
     *                   Element ist optional und wiederholbar, kann also nicht oder beliebig oft auftreten
     ,                   mit ',' getrennte Elemente muessen genau in der beschriebenen Reihenfolge vorkommen
     ()                  gruppiert
     weitere Schluesselwoerter/Zeichen:
     EMPTY:              keinen Inhalt
     ANY:                beliebigen Inhalt
     keine Angabe        Element ist obligatorisch, es muss genau einmal auftreten   
     ?                   Element ist optional, kann also nicht oder genau einmal auftreten.
     |                   genau eines der mit '|' getrennte Elemente muss vorkommen -->
<!ELEMENT urlset (aside,url+)> 

<!-- Attribut-Deklaration:
     CDATA:              Akronym fuer engl. character data => Zeichendaten, ist ein Datentyp der Attributdeklaration
     weitere Attribut-Datentypen: 
     NMTOKEN/NMTOKENS:   eine zusammenhängende Zeichenkette aus Ziffern, Buchstaben 
                         und ».«, »_« sowie »-« (NMTOKEN) oder mehrere solche Zeichenketten (NMTOKENS)
     ID:                 eine eindeutige ID 
     IDREF/IDREFS:       eine Referenz auf eine solche ID (IDREF) oder mehrere davon (IDREFS) 
     Enumeration:        eine Auflistung konkreter Werte, die im Attribut stehen dürfen, 
                         auch mit Default-Wert; z.B.: (a|b|c) "a"
     ENTITY/ENTITIES:    Referenzen auf in der DTD deklarierte Entities
     NOTATION/NOTATIONS: Notationen, eher selten
     => diese Attribut-Datentypen lassen kein Festlegen von Attributen zu, 
        die nur Zahlen oder Buchstaben enthalten duerfen (XSD:Schema ermoeglicht dies)
     Attribut-Vorgaben:
     #REQUIRED:          Attribute 'name' muss vorkommen  
     weitere Moeglichkeiten:
     #IMPLIED:           Attribute ist optional 
     #FIXED:             Attribute hat immer einen festen Wert  -->
<!ATTLIST urlset name CDATA #REQUIRED>  

<!ELEMENT aside (text)>
<!ATTLIST aside headline CDATA #REQUIRED>

<!ELEMENT url (loc*,lastmod*,priority*,text*,url*)> 
<!ATTLIST url name CDATA #REQUIRED> 

<!-- PCDATA Akronym fuer engl. parsed character data, ist eine Elementtypdeklaration (Elementinhalt/Content Model)
     => Textblock wird ebenfalls syntaktisch vom Parser analysiert
     => wird fuer gemischte Inhalte des Dokuments verwendet 
        (Inhalte, die auch andere Elemente oder Textbloecke enthalten, dh Element KANN aus Zeichendaten bestehen) -->
<!ELEMENT loc (#PCDATA)>
<!ELEMENT lastmod (#PCDATA)>
<!ELEMENT priority (#PCDATA)>
<!ELEMENT text (#PCDATA)>

=== mediafreak/jpr_web_sose13_abschlussprojekt/xml/sitemap/sitemap.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE urlset SYSTEM "sitemap.dtd"> <!-- Doctype-Deklaration fuer die dtd -->
<!-- ruft xslt-Datei auf -->
<?xml-stylesheet type="text/xsl" href="../sitemap.xsl"?>
<!-- Sitemap fuer Hauptnavigation, koennte noch auf Top-Nav ausgeweitet werden -->
<urlset name="Sitemap">
  <!-- aside-Bereich -->
  <aside headline="Aufgabe 3">
    <text>Erstellen Sie eine XML-Datei mit unnummerierten Kapitel체berschriften (auch Unterkapitel) und erstellen 
          Sie eine XSLT-Datei, so dass als Ergebnis eine HTML-Datei erzeugt wird, die nummerierte Kaptel체berschriften enth채lt. F체r die XML-Datei legen Sie noch ein entsprechendes Vokabular fest, als DTD oder Schema-Datei.
    </text>
  </aside>
  
  <!-- Url-Eintrag Hauptnavigation, alle vier Kindknoten koennen, muessen derzeit aber nicht angegeben werden -->
  <url name="Home">
    <!-- url -->
    <loc>../../index.html</loc>
    <!-- letzte Veraenderung, wird aber noch nicht ausgewertet -->
    <lastmod>2013-05-24T22:48:06+00:00</lastmod>
    <!-- letzte Veraenderung, wird aber noch nicht ausgewertet -->
    <priority>1.00</priority>
    <!-- beschreibener Text -->
    <text>Das ist die Willkommensseite</text>
  </url>

  <url name="Die Band">
    <loc>../../html/band.html</loc>
    <lastmod>2013-05-24T22:48:06+00:00</lastmod>
    <priority>0.80</priority>
    <text>Hier stellt sich unsere Band vor</text>
  </url>

  <url name="Die Musik">
    <loc>../../html/musik.html</loc>
    <lastmod>2013-05-24T22:48:06+00:00</lastmod>
    <priority>0.80</priority>
    <text>Alles rund um die Musik</text>
    <!-- Url fuer Unternavigation -->
    <url name="Steelpans/-drums">
      <loc>../../html/musik.html</loc>
      <lastmod>2013-05-24T22:48:06+00:00</lastmod>
      <priority>0.80</priority>
      <text>Steelpans spiele</text>
      <url name="Tenor">
        <text>Tenor-Pan</text>
        <url name="C1"/>
        <url name="C2">
          <text>test</text>
        </url>
        <url name="C3"/>
        <url name="C4"/>
      </url>
      <url name="Sopran"/>
    </url>
    <url name="Repertoire">
      <loc>../../html/repertoire.html</loc>
      <lastmod>2013-05-24T22:48:06+00:00</lastmod>
      <priority>0.80</priority>
    </url>
    <url name="CD bestellen"/>
    <url name="Links"/>
  </url>

  <url name="Termine">
    <loc>../termine/termine.xml?0?3?T</loc>
    <lastmod>2013-06-10T07:10:16+00:00</lastmod>
    <priority>0.80</priority>
  </url>
  <url name="Buchung"/>
  <url name="Presse"/>
  <url name="Galerie">
    <loc>../galerie/galerie.xml?0?2?G</loc>
    <lastmod>2013-06-10T07:10:16+00:00</lastmod>
    <priority>0.80</priority>
    <url name="Event 1">
      <loc>../galerie/galerie.xml?0?2?G</loc>
      <lastmod>2013-05-24T22:48:06+00:00</lastmod>
      <priority>0.80</priority>
    </url>
    <url name="Event 2">
      <loc>../galerie/galerie.xml?1?2?G</loc>
      <lastmod>2013-05-24T22:48:06+00:00</lastmod>
      <priority>0.80</priority>
      <text>Bilder von unserem Event</text>
    </url>
  </url>
</urlset>
